sonar.projectKey=flowboard-frontend-app
sonar.organization=kanhiya-sh

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/.angular/**,**/karma.conf.js,**/*.module.ts,**/environments/**,**/main.ts,**/polyfills.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/flowboard-frontend/lcov.info
sonar.typescript.lcov.reportPaths=coverage/flowboard-frontend/lcov.info

sonar.sourceEncoding=UTF-8
